package main

import (
	"testing"

	acp "github.com/coder/acp-go-sdk"
)

// TestMapSessionUpdate feeds synthetic ACP session/update notifications
// through mapSessionUpdate — the pure mapping function acpDriver.
// SessionUpdate delegates to — and checks the resulting agentEvent against
// acp-integration.md's Prompt mapping table (work item 8): message chunk →
// "message", thought chunk → "thought", tool_call → "tool-call",
// tool_call_update with a terminal status → "tool-result", plan → "plan",
// and a non-terminal tool_call_update produces nothing.
func TestMapSessionUpdate(t *testing.T) {
	cases := []struct {
		name string
		in   acp.SessionUpdate
		want agentEvent
		ok   bool
	}{
		{
			name: "message chunk",
			in:   acp.UpdateAgentMessageText("hello"),
			want: agentEvent{Kind: "message", Text: "hello"},
			ok:   true,
		},
		{
			name: "thought chunk",
			in:   acp.UpdateAgentThoughtText("thinking..."),
			want: agentEvent{Kind: "thought", Text: "thinking..."},
			ok:   true,
		},
		{
			name: "tool call start",
			in: acp.StartToolCall("call-1", "query",
				acp.WithStartRawInput(map[string]any{"query": "foo(X)?"})),
			want: agentEvent{
				Kind:       "tool-call",
				ToolCallID: "call-1",
				ToolName:   "query",
				ToolArgs:   `{"query":"foo(X)?"}`,
			},
			ok: true,
		},
		{
			name: "tool call update in progress is not a result",
			in: acp.UpdateToolCall("call-1",
				acp.WithUpdateStatus(acp.ToolCallStatusInProgress)),
			ok: false,
		},
		{
			name: "tool call update completed",
			in: acp.UpdateToolCall("call-1",
				acp.WithUpdateStatus(acp.ToolCallStatusCompleted),
				acp.WithUpdateContent([]acp.ToolCallContent{
					acp.ToolContent(acp.TextBlock("14 rows")),
				})),
			want: agentEvent{
				Kind:       "tool-result",
				ToolCallID: "call-1",
				Result:     "14 rows",
				IsError:    false,
			},
			ok: true,
		},
		{
			name: "tool call update failed",
			in: acp.UpdateToolCall("call-1",
				acp.WithUpdateStatus(acp.ToolCallStatusFailed),
				acp.WithUpdateContent([]acp.ToolCallContent{
					acp.ToolContent(acp.TextBlock("boom")),
				})),
			want: agentEvent{
				Kind:       "tool-result",
				ToolCallID: "call-1",
				Result:     "boom",
				IsError:    true,
			},
			ok: true,
		},
		{
			name: "plan",
			in: acp.UpdatePlan(
				acp.PlanEntry{Content: "read schema", Status: acp.PlanEntryStatusCompleted},
				acp.PlanEntry{Content: "write rules", Status: acp.PlanEntryStatusInProgress},
			),
			want: agentEvent{
				Kind: "plan",
				PlanEntries: []agentPlanEntry{
					{Content: "read schema", Status: "completed"},
					{Content: "write rules", Status: "in_progress"},
				},
			},
			ok: true,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, ok := mapSessionUpdate(c.in)
			if ok != c.ok {
				t.Fatalf("ok = %v, want %v (event: %+v)", ok, c.ok, got)
			}
			if !ok {
				return
			}
			if got.Kind != c.want.Kind {
				t.Errorf("Kind = %q, want %q", got.Kind, c.want.Kind)
			}
			if got.Text != c.want.Text {
				t.Errorf("Text = %q, want %q", got.Text, c.want.Text)
			}
			if got.ToolCallID != c.want.ToolCallID {
				t.Errorf("ToolCallID = %q, want %q", got.ToolCallID, c.want.ToolCallID)
			}
			if c.want.ToolName != "" && got.ToolName != c.want.ToolName {
				t.Errorf("ToolName = %q, want %q", got.ToolName, c.want.ToolName)
			}
			if c.want.ToolArgs != "" && got.ToolArgs != c.want.ToolArgs {
				t.Errorf("ToolArgs = %q, want %q", got.ToolArgs, c.want.ToolArgs)
			}
			if got.Result != c.want.Result {
				t.Errorf("Result = %q, want %q", got.Result, c.want.Result)
			}
			if got.IsError != c.want.IsError {
				t.Errorf("IsError = %v, want %v", got.IsError, c.want.IsError)
			}
			if c.want.Kind == "plan" {
				if len(got.PlanEntries) != len(c.want.PlanEntries) {
					t.Fatalf("PlanEntries = %+v, want %+v", got.PlanEntries, c.want.PlanEntries)
				}
				for i := range got.PlanEntries {
					if got.PlanEntries[i] != c.want.PlanEntries[i] {
						t.Errorf("PlanEntries[%d] = %+v, want %+v", i, got.PlanEntries[i], c.want.PlanEntries[i])
					}
				}
			}
		})
	}
}

// TestPermissionEvent checks permissionEvent's mapping of a
// RequestPermissionRequest into the "permission" agentEvent's fields —
// RequestID is generated by the caller (acpDriver.RequestPermission), so
// this only exercises the params → agentEvent projection.
func TestPermissionEvent(t *testing.T) {
	req := acp.RequestPermissionRequest{
		ToolCall: acp.ToolCallUpdate{
			ToolCallId: "call-9",
			Title:      acp.Ptr("set_rules"),
			RawInput:   map[string]any{"text": "p(X) :- q(X)."},
		},
		Options: []acp.PermissionOption{
			{OptionId: "allow", Name: "Allow", Kind: acp.PermissionOptionKindAllowOnce},
			{OptionId: "reject", Name: "Reject", Kind: acp.PermissionOptionKindRejectOnce},
		},
	}

	ev := permissionEvent("perm-1", req)

	if ev.Kind != "permission" {
		t.Fatalf("Kind = %q, want %q", ev.Kind, "permission")
	}
	if ev.RequestID != "perm-1" {
		t.Errorf("RequestID = %q, want %q", ev.RequestID, "perm-1")
	}
	if ev.ToolCallID != "call-9" {
		t.Errorf("ToolCallID = %q, want %q", ev.ToolCallID, "call-9")
	}
	if ev.ToolName != "set_rules" {
		t.Errorf("ToolName = %q, want %q", ev.ToolName, "set_rules")
	}
	if len(ev.Options) != 2 {
		t.Fatalf("Options = %+v, want 2 entries", ev.Options)
	}
	if ev.Options[0].ID != "allow" || ev.Options[0].Kind != "allow_once" {
		t.Errorf("Options[0] = %+v", ev.Options[0])
	}
	if ev.Options[1].ID != "reject" || ev.Options[1].Kind != "reject_once" {
		t.Errorf("Options[1] = %+v", ev.Options[1])
	}
}
